name: Deploy QA

on:
  push:
    branches: ["test-qa"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ENV_DIR: infra/terraform/envs/qa
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials (Learner Lab)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform apply (QA)
        working-directory: ${{ env.ENV_DIR }}
        run: |
          terraform init
          terraform apply -auto-approve             -var="aws_region=$AWS_REGION"             -var="repo_url=https://github.com/${{ github.repository }}"             -var="git_ref=test-qa"
